AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'fondy.gemspec'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/EmptyLines:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
